main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('data/', views.data, name='data')
]

story/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
import requests

def home(request):
    return render(request, 'main/home.html')

def data(request):
    keyword = request.GET['q']
    url = 'https://www.googleapis.com/books/v1/volumes?q=' + keyword
    info = requests.get(url)
    data = json.loads(info.content)
    return JsonResponse(data, safe=False)

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 8</title>
{% endblock meta %}

{% block content %}
<h1 class="display-4 text-center mt-5 pt-5">Story-8</h1>
<div class="container pt-5">
  <input id="keyword" class="mb-5" placeholder="Masukkan kata kunci">

  <table id="result" class="table table-borderless text-center">
  
  </table>
</div>


<script type="text/javascript">
$(document).ready( function() {
    url_default = '/data?q=harry potter';
    $.ajax({
      url: url_default,
      success: function(tmp) {
        var obj_default = $('#result');
        for (i = 0; i < tmp.items.length; i++) {
          var def_title = tmp.items[i].volumeInfo.title;
          var def_author = tmp.items[i].volumeInfo.authors;
          var def_publisher = tmp.items[i].volumeInfo.publisher;
          var def_thumbnail = tmp.items[i].volumeInfo.imageLinks.smallThumbnail;
          obj_default.append('<tr> <td> ' + (i+1) + '</td> <td>' + def_title + '</td> <td>' + def_author + '</td> <td>' + def_publisher +' </td> <td> <img src=' + def_thumbnail + '> </td>');
        }
      }
    })
  })

  $("#keyword").keyup( function() {
    var content = $("#keyword").val();
    var url = '/data?q=' + content;
  
    $.ajax({
      url: url,
      success: function(result) {
        var obj_result = $("#result");
        obj_result.empty();

        for (i = 0; i < result.items.length; i++) {
          var tmp_title = result.items[i].volumeInfo.title;
          var tmp_author = result.items[i].volumeInfo.authors;
          var tmp_publisher = result.items[i].volumeInfo.publisher;
          var tmp_thumbnail = result.items[i].volumeInfo.imageLinks.smallThumbnail;
          obj_result.append('<tr> <td> ' + (i+1) + '</td> <td>' + tmp_title + '</td> <td>' + tmp_author + '</td> <td>' + tmp_publisher +' </td> <td> <img src=' + tmp_thumbnail + '> </td>');
        }
      }
    })
  })
</script>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <!-- <h1>Hello, world!</h1> -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <a class="navbar-brand" href="#home">Ghifari</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <!-- <a class="nav-item nav-link page-scroll" href="#home">Home <span class="sr-only">(current)</span></a> -->
          <a class="nav-item nav-link" href="{% url 'main:home' %}">Home</a>
        </div>
      </div>
      </div>
    </nav>
    {% block content %}
    {% endblock content %}
</body>

</html>